#!/bin/bash
# Copyright (C) 2016 Kazumasa Kohtaka <kkohtaka@gmail.com> All right reserved

# Git Completion

source $HOME/.git/contrib/completion/git-completion.bash

# Node.js / NVM

[[ -s "$HOME/.nvm/nvm.sh" ]] && source "$HOME/.nvm/nvm.sh"

export PATH=$PATH:./node_modules/.bin

