#!/bin/bash
# Copyright (C) 2016 Kazumasa Kohtaka <kkohtaka@gmail.com> All right reserved

# Git Completion

source $HOME/.git/contrib/completion/git-completion.bash

# Node.js / NVM

export NVM_DIR=~/.nvm
[[ -s "$(brew --prefix nvm)/nvm.sh" ]] && source "$(brew --prefix nvm)/nvm.sh"

export PATH=$PATH:./node_modules/.bin

