#!/bin/bash
# Copyright (C) 2016 Kazumasa Kohtaka <kkohtaka@gmail.com> All right reserved

# Git Completion

source $HOME/.git/contrib/completion/git-completion.bash

# Go

export GOPATH=$HOME/golang
export PATH=$PATH:$GOPATH/bin
